FiligranHQ/xtm-hub

portal-front/app/(public)/cybersecurity-solutions/[slug]/[docSlug]/page.tsx

[frontend] the download number is not displayed on public pages #721
Related #721

[frontend] the download number is not displayed on public pages #721

---

portal-front/src/components/ui/share-link/share-link-button.tsx

> Change the toast content into description
Go to a custom dashboard/ingestion feed 
Click the share button 
You should see a better toast !
Related #730

[frontend] improve(Share link): Improve UI #730

---

portal-api/package.json
portal-api/yarn.lock

Upgrade zod version to benefit from v4 features
E2E should be enough to see if upgrade breaks something

chore: upgrade zod

---

portal-api/src/__generated__/resolvers-types.ts
portal-api/src/modules/services/csv-feeds/csv-feeds.graphql
portal-api/src/modules/services/custom-dashboards/custom-dashboards.graphql
portal-api/src/modules/services/document/document.domain.ts
portal-api/src/modules/services/document/document.test.ts
portal-api/src/modules/services/obas-scenarios/obas-scenarios.graphql
portal-e2e-tests/tests/tests_files/custom-dashboards.spec.ts
portal-front/messages/en.json
portal-front/messages/fr.json
portal-front/package.json
portal-front/schema.graphql
portal-front/src/components/service/csv-feeds/[serviceInstanceId]/csv-feed-add-sheet.tsx
portal-front/src/components/service/csv-feeds/[serviceInstanceId]/csv-feed-form.tsx
portal-front/src/components/service/csv-feeds/[serviceInstanceId]/csv-feed-update-sheet.tsx
portal-front/src/components/service/csv-feeds/csv-feed.graphql.ts
portal-front/src/components/service/custom-dashboards/[serviceInstanceId]/custom-dashboard-form.tsx
portal-front/src/components/service/custom-dashboards/[serviceInstanceId]/custom-dashboard-sheet.tsx
portal-front/src/components/service/custom-dashboards/[serviceInstanceId]/custom-dashboard-update-form.tsx
portal-front/src/components/service/custom-dashboards/[serviceInstanceId]/custom-dashboard-update.tsx
portal-front/src/components/service/custom-dashboards/custom-dashboard.graphql.ts
portal-front/src/components/service/obas-scenarios/[serviceInstanceId]/obas-scenario-add-sheet.tsx
portal-front/src/components/service/obas-scenarios/[serviceInstanceId]/obas-scenario-form.tsx
portal-front/src/components/service/obas-scenarios/[serviceInstanceId]/obas-scenario-update-sheet.tsx
portal-front/src/components/service/obas-scenarios/obas-scenario.graphql.ts
portal-front/src/components/ui/select-users.tsx
portal-front/yarn.lock

> This PR allow the user to choose an uploader for shareable resource 
> I have also refactored the custom-dashboard-update-form with Autoform 👯‍♂️ 
Nothing should change on frontend except the new file : uploader !  
PLease think to : 
Add a new Custom dashboard 
Edit it 
Add a new CSVFeed 
Edit it 
Add a new scenrio OBAS
Edit it
Related #706

[frontend] : Choose the uploader on creation&edition of IntegrationFeeds, CustomDashboards and OBAS scenario #706

---

portal-api/src/modules/user_service/user_service.domain.ts

This pull request updates the query logic in the `loadUserServiceByUser` function to fix a security issue

[backend] fix(user_service): a bad OR condition leads to bypass security

---

chart/Chart.yaml
chart/templates/api.yaml
chart/templates/elasticsearch.yaml
chart/values.yaml

[infra] chore: elasticsearch deployment

---

portal-api/src/security/access.ts
portal-api/src/security/layer/user-service.ts

Add security layer for UserService query.
Related #issueNumber

[backend] security(user_service): add user service security layer

---

apps/portal-front/app/redirect/[identifier]/resource.ts
package.json
yarn.lock

Use Github stylus version because the npm one is removed and not found during CI build.
Build must pass.

fix(ci): use github stylus version because npm one is removed

---

apps/portal-front/app/(embed)/layout.tsx
apps/portal-front/messages/en.json
apps/portal-front/src/components/enroll/form/organization.tsx

> Improve design on enrollment window
Enroll a new instance
Enjoy the design

[frontend] styles(embed): rework embed design (#65)

---

apps/portal-front/src/components/profile/index.tsx

Pass on all our toasters
They all should be iline, no sentences as title 
Related #816

[frontend] ui: Improve toasters #816

---

apps/portal-api/src/modules/common/error-code.ts
apps/portal-api/src/modules/users/users.admin.app.ts
apps/portal-api/src/modules/users/users.domain.ts
apps/portal-api/src/modules/users/users.profile.app.ts
apps/portal-api/src/modules/users/users.resolver.ts

We wish to improve readability of our feature by decoupling behaviour between resolver, app service and domain service.
Either with the frontend or with the GraphQL playground:
- edit an user as an admin
- edit a me user
Related #issueNumber

[backend] refactor: use user edition app in user resolver

---

apps/portal-api/src/modules/common/error-code.ts
apps/portal-api/src/modules/services/enrollment/enrollment.app.test.ts
apps/portal-api/src/modules/services/enrollment/enrollment.app.ts
apps/portal-api/src/modules/services/enrollment/enrollment.resolver.ts
apps/portal-front/messages/en.json
apps/portal-front/messages/fr.json

- make user facing translation coherent
Translation update only, no needs to test
Related #65

[backend/frontend] refactor: replace enroll by register in translations

---

apps/portal-front/app/redirect/[identifier]/register-opencti.ts
apps/portal-front/app/redirect/[identifier]/unregister-opencti.ts
apps/portal-front/src/components/service/document/one-click-deploy/one-click-deploy.tsx
apps/portal-front/src/components/service/document/shareable-resource-slug.test.tsx
apps/portal-front/src/components/service/document/shareable-resource-slug.tsx
apps/portal-front/src/hooks/useOrganizationCapabilities.tsx
apps/portal-front/src/utils/constant.ts

Remove feature flags and associated code for OpenCTI platform registration and one click deploy features.
- register an OpenCTI platform
- deploy a custom dashboard in one click
- deploy a csv feed in one click
Related #65

[backend/frontend] chore: remove feature flags for release

---

.github/workflows/dockerbuild-ci.yml
apps/portal-e2e-tests/.gitignore
apps/portal-e2e-tests/Dockerfile
apps/portal-e2e-tests/package.json
apps/portal-e2e-tests/playwright.config.ts
apps/portal-e2e-tests/tests/fixtures/baseFixtures.js
apps/portal-front/package.json
package.json
xtm-hub-dev/docker-compose-ci.yml
yarn.lock

The idea is to provide an overview of how different end-to-end processes are executed, without having to go through the logs to identify each issue.
Launch the PR and see the report display in the PR comment

[e2e] add CTRF report to display in PR comment

---

apps/portal-front/src/components/admin/user/user-list-page.tsx
apps/portal-front/src/utils/constant.ts

add a feature flag to pending user page display
Users page should not be displayed when feature flag is not activated
Related #470

[backend] - feature(pendingUser) add feature flag #470

---

apps/portal-api/src/__generated__/resolvers-types.ts
apps/portal-api/src/migrations/20250813132617_add-user-platform-token.js
apps/portal-api/src/model/kanel/public/User.ts
apps/portal-api/src/modules/common/error-code.ts
apps/portal-api/src/modules/services/document/document-download-endpoint.ts
apps/portal-api/src/modules/services/registration/registration.app.test.ts
apps/portal-api/src/modules/services/registration/registration.app.ts
apps/portal-api/src/modules/services/registration/registration.graphql
apps/portal-api/src/modules/services/registration/registration.resolver.ts
apps/portal-api/src/modules/users/users.graphql
apps/portal-front/schema.graphql
apps/portal-front/src/components/register/register.graphql.ts
apps/portal-front/src/components/service/document/one-click-deploy/one-click-deploy.tsx
apps/portal-front/src/components/service/document/one-click-deploy/one-platform-display.tsx
apps/portal-front/src/components/service/document/one-click-deploy/useOneClickDeployTab.tsx
apps/portal-front/src/hooks/useExternalTab.tsx

- add platform token to users
- provide mutation to refresh platform token
- communicate with OpenCTI via postMessage to send token
Related #849

[backend/frontend] feat: add ability to download document with new token

---

apps/portal-api/src/__generated__/resolvers-types.ts
apps/portal-api/src/migrations/20250905125640_add-opencti-version-contract.js
apps/portal-api/src/modules/services/registration/registration.app.test.ts
apps/portal-api/src/modules/services/registration/registration.app.ts
apps/portal-api/src/modules/services/registration/registration.deprecated.graphql
apps/portal-api/src/modules/services/registration/registration.deprecated.resolver.test.ts
apps/portal-api/src/modules/services/registration/registration.domain.test.ts
apps/portal-api/src/modules/services/registration/registration.domain.ts
apps/portal-api/src/modules/services/registration/registration.graphql
apps/portal-api/src/modules/services/registration/registration.resolver.ts
apps/portal-front/app/(embed)/register/[identifier]/page-loader.tsx
apps/portal-front/schema.graphql
apps/portal-front/src/components/registration/register/index.tsx

We need to register OpenCTI platform version 
- Add at the registration
- Update on the regular checkConnectivity to keep the version up to date.
- Run in parallel OpenCTI in master and on [issue/hub-919](https://github.com/OpenCTI-Platform/opencti/pull/12287)
- For each branch : 
- Try to register and unregister on each platform
- Go to Filigran experience to check if the version is updated/call the mutation to refresh OpenCTI data in XTM Hub
Related #919

[backend/frontend] register OpenCTI platform with version #919

---

xtm-hub-dev/docker-compose-ci.yml
xtm-hub-dev/docker-compose.yml

Update minio version 
Related #963

[config] update minio version RELEASE.2025-06-13T11-33-47Z #963

---

renovate.json

Modify renovate concurrent to open 5 PR instead of 2

[config] modify prConcurrent renovate 2 to 5

---

.github/workflows/dockerbuild-ci.yml

Launch dockerbuild when e2e is modified

[config] add e2e-tests path in dockerbuild

---

apps/portal-api/src/modules/services/csv-feeds/csv-feeds.resolver.ts
apps/portal-api/src/modules/services/custom-dashboards/custom-dashboards.resolver.ts
apps/portal-api/src/modules/services/document/document.resolver.ts
apps/portal-api/src/modules/services/openaev-scenarios/openaev-scenarios.resolver.ts
apps/portal-api/src/modules/services/registration/registration.domain.ts
apps/portal-api/src/modules/services/service-instance.domain.ts
apps/portal-api/src/modules/subcription/subscription.app.ts
apps/portal-api/src/modules/subcription/subscription.domain.ts
apps/portal-api/src/modules/subcription/subscription.helper.ts
apps/portal-api/src/modules/subcription/subscription.resolver.ts
apps/portal-api/src/modules/subscription.const.ts
apps/portal-api/src/modules/user_service/user-service.helper.ts
apps/portal-api/src/server/mail-service.ts

> Briefly describe the purpose and context of this PR. Include relevant screenshots or screen recordings for the product team.
- refactor subscription add feature
- add an app layer
- put DB calls in domain layer
- rename feature in app layer
- remove some dead code 
> Provide step-by-step instructions to test your changes. Include screenshots of your local testing results.
- subscribe to a service
- check if everything went well
- Related to #990 
> Any additional context, dependencies, or concerns reviewers should know about.

[backend] refactor: move add subcription mutation to new app layer

---

apps/portal-api/src/modules/services/csv-feeds/csv-feeds.resolver.ts
apps/portal-api/src/modules/services/custom-dashboards/custom-dashboards.resolver.ts
apps/portal-api/src/modules/services/document/document.resolver.ts
apps/portal-api/src/modules/services/openaev-scenarios/openaev-scenarios.resolver.ts
apps/portal-api/src/modules/services/registration/registration.domain.ts
apps/portal-api/src/modules/services/service-instance.domain.ts
apps/portal-api/src/modules/subcription/subscription.app.ts
apps/portal-api/src/modules/subcription/subscription.domain.ts
apps/portal-api/src/modules/subcription/subscription.helper.ts
apps/portal-api/src/modules/subcription/subscription.resolver.ts
apps/portal-api/src/modules/subscription.const.ts
apps/portal-api/src/modules/user_service/user-service.helper.ts
apps/portal-api/src/server/mail-service.ts

> Briefly describe the purpose and context of this PR. Include relevant screenshots or screen recordings for the product team.
Copy of https://github.com/FiligranHQ/xtm-hub/pull/992 because commit disappeared from development
Already tested and validated

[backend] refactor: move add subcription mutation to new app layer

---

apps/portal-api/src/modules/subcription/subscription.app.ts
apps/portal-api/src/modules/subcription/subscription.resolver.ts
apps/portal-api/src/modules/user_service/service-capability/subscription-capability.domain.ts

> Briefly describe the purpose and context of this PR. Include relevant screenshots or screen recordings for the product team.
- create app layer method for `addSubscriptionInService` mutation
> Provide step-by-step instructions to test your changes. Include screenshots of your local testing results.
- go to the `Services` page in admin section
- click on `SUBSCRIBE ORGANIZATION` button
- fill the form and confirm
- check subscription is added
- Related to #990 
> Any additional context, dependencies, or concerns reviewers should know about.

[backend] refactor: move subscribe organization to app layer
